'use strict';

angular.module('workingRoom')
    .config(function ($translateProvider) {
        $translateProvider.translations('fr', {
            // LANGUAGE_CHOICE_FR: 'Français',
            // LANGUAGE_CHOICE_EN: 'Anglais',
            // LANGUAGE_CHOICE_ES: 'Espagnol',
                HOME_PAGE_TITLE: 'Modules',
                HOME_PAGE_MODULES_STAT_CPM: 'STATISTIQUES',
                HOME_PAGE_MODULES_TICKETS_CPM: 'TICKETS',
                SIDENAV_MODULES: 'Modules',
                SIDENAV_PROFILE: 'Profil',
                SIDENAV_ADMIN: 'Administration',
                SIDENAV_LOGOUT: 'Déconnexion',
                PROFILE_TITLE: 'Profil',
                PROFILE_CONNECT: 'Connecté',
                PROFILE_CONNECTED: 'Dernière connexion : ',
                PROFILE_BUTTON_MODIFY: 'Modifier le profil',
                PROFILE_BUTTON_DEL: 'Suppression du profil',
                EDIT_PROFIL_NAME: 'Nom',
                EDIT_PROFIL_GROUPS: 'Ajouter un groupe',
                EDIT_PROFIL_USER: 'Utilisateur',
                EDIT_PROFIL_ADMIN: 'Administrateur',
                EDIT_PROFIL_MAIL: 'CHANGER L\'EMAIL',
                EDIT_PROFIL_PWD: 'CHANGER LE MOT DE PASSE',
                EDIT_PROFIL_SAVE: 'Enregistrer',
                EDIT_PROFIL_CANCEL: 'Annuler',
                ADMIN_TITLE: 'Administration',
                ADMIN_MODULE_TAB: 'MODULES',
                ADMIN_MODULE_CPM_DEL: 'SUPPRIMER',
                ADMIN_MODULE_CPM_MODIFY: 'MODIFIER',
                ADMIN_MODULE_ESCALADE_DEL_: 'SUPPRIMER',
                ADMIN_MODULE_ESCALADE_MODIFY: 'MODIFIER',
                ADMIN_MODULE_VOYAGE_DEL: 'SUPPRIMER',
                ADMIN_MODULE_VOYAGE_MODIFY: 'MODIFIER',
                ADMIN_MODULES_BUTTON_CREATE: 'Créer un module',
                BUTTON_CREATE_MODULE: 'CRÉER',
                BUTTON_CLOSE_CREATION_MODULE: 'FERMER',
                CREATE_NAME_MODULE: 'Nom du module',
                MODIFY_MODULE_NAME: 'Nom du module',
                MODIFY_MODULE_FIELDS: 'Nom du nouveau champ pour les tickets',
                MODIFY_MODULE_BUTTON_CLOSE: 'FERMER',
                MODIFY_MODULE_BUTTON_SAVE: 'SAUVEGARDER',
                MODIFY_FIELDS_NAME: 'Nom',
                MODIFY_FIELDS_BUTTON_DEL: 'SUPPRIMER',
                MODIFY_FIELDS_BUTTON_CLOSE: 'FERMER',
                MODIFY_FIELDS_BUTTON_SAVE: 'SAUVEGARDER',
                DELETE_MODULE_CARE: 'Attention',
                DELETE_MODULE_QUESTION: 'Voulez-vous vraiment supprimer ce module ?',
                DELETE_MODULE_YES: 'OUI',
                DELETE_MODULE_NO: 'NON',
                ADMIN_GROUPS_TAB: 'GROUPES',
                ADMIN_GROUPS_BUTTON_CREATE: 'Créer un groupe',
                ADMIN_GROUPS_BUTTON_DEL: 'SUPPRIMER',
                ADMIN_GROUPS_BUTTON_MODIFY: 'MODIFIER',
                ADMIN_USERS_TAB: 'UTILISATEURS',
                ADMIN_USERS_BUTTON_CREATE: 'Créer un utilisateur',
                TICKET_TABLE_NAME: 'Nom',
                TICKET_TABLE_SUBJECT: 'Sujet',
                TICKET_TABLE_CREATED: 'Date de Création',
                TICKET_TABLE_LAST_REPLY: 'Dernière Réponse Par',
                TICKET_CREATE: 'Créer un ticket',
                TICKET_BUTTON_SEARCH: 'Rechercher un ticket',
                TICKET_BUTTON_EDIT: "Edition du module"
        }).useSanitizeValueStrategy('escape').preferredLanguage('fr');
    });
