'use strict';

angular.module('workingRoom')
    .config(function ($translateProvider) {
        $translateProvider.translations('pl', {
            // LANGUAGE_CHOICE_FR: 'Français',
            // LANGUAGE_CHOICE_EN: 'Anglais',
            // LANGUAGE_CHOICE_ES: 'Espagnol',
                HOME_PAGE_TITLE: 'Moduły',
                HOME_PAGE_MODULES_STAT_CPM: 'STATYSTYKA',
                HOME_PAGE_MODULES_TICKETS_CPM: 'TICKETS',
                HOME_PAGE_MODULES_STAT_ESC: 'STATYSTYKA',
                HOME_PAGE_MODULES_TICKETS_ESC: 'TICKETS',
                HOME_PAGE_MODULES_STAT_VOY: 'STATYSTYKA',
                HOME_PAGE_MODULES_TICKETS_VOY: 'TICKETS',
                SIDENAV_MODULES: 'Moduły',
                SIDENAV_PROFILE: 'Profil',
                SIDENAV_ADMIN: 'Administracja',
                SIDENAV_LOGOUT: 'Wyloguj',
                PROFILE_TITLE: 'Profil',
                PROFILE_CONNECT: 'Połączony',
                PROFILE_CONNECTED: 'Ostatnie połączonie : ',
                PROFILE_BUTTON_MODIFY: 'Zmodyfikować profil',
                PROFILE_BUTTON_DEL: 'Usuń profil',
                EDIT_PROFIL_NAME: 'Nazwa',
                EDIT_PROFIL_GROUPS: 'Dodaj grupę',
                EDIT_PROFIL_USER: 'Użytkownik',
                EDIT_PROFIL_ADMIN: 'Administrator',
                EDIT_PROFIL_MAIL: 'ZMIEŃ ADRES E-MAIL',
                EDIT_PROFIL_PWD: 'ZMIEŃ HASŁO',
                EDIT_PROFIL_SAVE: 'Zgraj',
                EDIT_PROFIL_CANCEL: 'Anuluj',
                ADMIN_TITLE: 'Administracja',
                ADMIN_MODULE_TAB: 'MODUŁY',
                ADMIN_MODULE_CPM_DEL: 'USUNĄĆ',
                ADMIN_MODULE_CPM_MODIFY: 'ZMODYFIKOWAĆ',
                ADMIN_MODULE_ESCALADE_DEL_: 'USUNĄĆ',
                ADMIN_MODULE_ESCALADE_MODIFY: 'ZMODYFIKOWAĆ',
                ADMIN_MODULE_VOYAGE_DEL: 'USUNĄĆ',
                ADMIN_MODULE_VOYAGE_MODIFY: 'ZMODYFIKOWAĆ',
                ADMIN_MODULES_BUTTON_CREATE: 'Utworzyć moduł',
                BUTTON_CREATE_MODULE: 'TWORZYĆ',
                BUTTON_CLOSE_CREATION_MODULE: 'WYSŁAĆ',
                CREATE_NAME_MODULE: 'Nazwa modułu',
                MODIFY_MODULE_NAME: 'Nazwa modułu',
                MODIFY_MODULE_FIELDS: 'Dodaj nazwę pola',
                MODIFY_MODULE_BUTTON_CLOSE: 'WYSŁAĆ',
                MODIFY_MODULE_BUTTON_SAVE: 'ZGRAJ',
                MODIFY_FIELDS_NAME: 'Nazwa',
                MODIFY_FIELDS_BUTTON_DEL: 'USUNĄĆ',
                MODIFY_FIELDS_BUTTON_CLOSE: 'WYSŁAĆ',
                MODIFY_FIELDS_BUTTON_SAVE: 'ZGRAJ',
                DELETE_MODULE_CARE: 'Ostrzeżenie',
                DELETE_MODULE_QUESTION: 'Czy na pewno chcesz usunąć ten moduł ?',
                DELETE_MODULE_YES: 'TAK',
                DELETE_MODULE_NO: 'NIE',
                ADMIN_GROUPS_TAB: 'GRUPY',
                ADMIN_GROUPS_BUTTON_CREATE: 'Tworzyć grupę',
                ADMIN_GROUPS_BUTTON_DEL: 'USUNĄĆ',
                ADMIN_GROUPS_BUTTON_MODIFY: 'ZMODYFIKOWAĆ',
                ADMIN_USERS_TAB: 'UŻYTKOWNIK',
                ADMIN_USERS_BUTTON_CREATE: 'Utworzyć użytkownika',
                TICKET_TABLE_NAME: 'Nazwa',
                TICKET_TABLE_SUBJECT: 'Temat',
                TICKET_TABLE_CREATED: 'Data utworzenia',
                TICKET_TABLE_LAST_REPLY: 'Ostatnia odpowiedź',
                TICKET_CREATE: 'Stworzyć  ticket',
                TICKET_BUTTON_SEARCH: 'Wyszukiwarka ticket',
                TICKET_BUTTON_EDIT: "Moduł edycji"
        })
    });
